"""Add onboarding_completed to CustomerData

Revision ID: 078a023d1ef7
Revises: b2890a7b4310
Create Date: 2025-08-27 09:08:29.141503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078a023d1ef7'
down_revision = 'b2890a7b4310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        # ▼▼▼ 既存の行にデフォルト値としてFalseを設定するよう指示を追加 ▼▼▼
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default='f'))
        # ▲▲▲ ここまで修正 ▲▲▲

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###