"""Add session_id to ConversationLog

Revision ID: 3b40f8fe75f5
Revises: 8909a64836fd
Create Date: 2025-08-26 00:46:06.868848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b40f8fe75f5'
down_revision = '8909a64836fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=False, server_default='legacy_session'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_log_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
