"""Add notification settings to CustomerData

Revision ID: 46a047cccb18
Revises: 078a023d1ef7
Create Date: 2025-08-27 15:09:31.990275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a047cccb18'
down_revision = '078a023d1ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_weekly_report', sa.Boolean(), nullable=False, server_default='t'))
        batch_op.add_column(sa.Column('report_day_of_week', sa.Integer(), nullable=False, server_default='1'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.drop_column('report_day_of_week')
        batch_op.drop_column('enable_weekly_report')

    # ### end Alembic commands ###
