"""Add LINE credentials to CustomerData

Revision ID: 7eb3c65f1877
Revises: 9a15170d5b27
Create Date: 2025-08-25 20:44:33.548421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb3c65f1877'
down_revision = '9a15170d5b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_channel_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('line_channel_secret', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.drop_column('line_channel_secret')
        batch_op.drop_column('line_channel_token')

    # ### end Alembic commands ###
