"""Add message color settings

Revision ID: 8739251801e9
Revises: fa22470b6b3c
Create Date: 2025-08-28 23:55:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8739251801e9'
down_revision = 'fa22470b6b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_message_color', sa.String(length=7), server_default='#3b5998', nullable=False))
        batch_op.add_column(sa.Column('bot_message_color', sa.String(length=7), server_default='#e9ecef', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.drop_column('bot_message_color')
        batch_op.drop_column('user_message_color')

    # ### end Alembic commands ###