"""Add chat button color setting

Revision ID: 900307d1bf90
Revises: 8739251801e9
Create Date: 2025-08-30 16:27:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900307d1bf90'
down_revision = '8739251801e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_button_color', sa.String(length=7), server_default='#3b5998', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.drop_column('chat_button_color')

    # ### end Alembic commands ###