"""Add LineUser model

Revision ID: 9a15170d5b27
Revises: 
Create Date: 2025-08-25 17:07:18.274374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a15170d5b27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_user_line_user_id'), ['line_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_user_line_user_id'))

    op.drop_table('line_user')
    # ### end Alembic commands ###
