"""Add uncertain_reply to CustomerData

Revision ID: 9cbb15c55306
Revises: 46a047cccb18
Create Date: 2025-08-27 23:54:05.079794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbb15c55306'
down_revision = '46a047cccb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncertain_reply', sa.String(length=500), nullable=False, server_default='申し訳ありませんが、わかりかねます。'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.drop_column('uncertain_reply')

    # ### end Alembic commands ###
