"""Add MenuItem model

Revision ID: b2890a7b4310
Revises: 3b40f8fe75f5
Create Date: 2025-08-26 23:43:00.682935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2890a7b4310'
down_revision = '3b40f8fe75f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('action_text', sa.String(length=50), nullable=False),
    sa.Column('customer_data_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_data_id'], ['customer_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_log_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_log_session_id'))

    op.drop_table('menu_item')
    # ### end Alembic commands ###
