"""Add ExampleQuestion model

Revision ID: c3566801afb0
Revises: 7eb3c65f1877
Create Date: 2025-08-25 22:01:23.370879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3566801afb0'
down_revision = '7eb3c65f1877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('customer_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_data_id'], ['customer_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example_question')
    # ### end Alembic commands ###
