"""Add public_id to CustomerData

Revision ID: fa22470b6b3c
Revises: 9cbb15c55306
Create Date: 2025-08-28 12:26:31.343159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa22470b6b3c'
down_revision = '9cbb15c55306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', postgresql.UUID(as_uuid=True), server_default=sa.func.gen_random_uuid(), nullable=False))
        batch_op.create_unique_constraint('uq_customer_data_public_id', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
